### PR TITLE
migrate from gulp 3 to gulp 4

### PR DESCRIPTION
**Pull request by CT1994**
So i really like this repo and want to use it with gulp 4.

I have migrated the project.
I have also added support for errors handing in any work to kill all workers and log out the error from the worker

### CODE REVIEW

**Comment by CT1994** [comment]
@rossipedia @uberska could you look into merging this asap please

https://github.com/rossipedia/gulp-cluster-src/issues/2#issue-348269377

**Comment by uberska** [comment]
@CT1994 : I am not an owner of this repository, and don't have merge access. Sorry.

**Comment by CT1994** [comment]
ah np @uberska hopefully @rossipedia can review and merge the changes for me

**Review by rossipedia — APPROVED** [review]
I don't see anything particularly worrying here. Thanks, I'll get this published

**Pull request merged**
